### ISSUE TITLE
Set worker instance name

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudman#93] opened 2019-06-07 15:05 UTC
With CloudMan 2.0, worker instance names are something like `default-yr9932d5`. Instead, they should include the cluster name and perhaps role for easier recognition on the provider dashboard.

**Comment by nuwang** [comment] 2019-11-10 19:47
Duplicate of: https://github.com/galaxyproject/cloudman/issues/100

**Closed by nuwang** 2019-11-10 19:47 UTC
