### ISSUE TITLE
Empty disk usage for FS 'transient_nfs'

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#38] opened 2016-02-12 17:36 UTC
AMI: ami-d5246abf, Name: Galaxy-CloudMan-1449500413.

Looks like a spurious warning message cluttering the Cluster info log:
```
17:29:12 - Empty disk usage for FS 'transient_nfs'
17:30:18 - Empty disk usage for FS 'transient_nfs'
17:31:21 - Empty disk usage for FS 'transient_nfs'
17:32:21 - Empty disk usage for FS 'transient_nfs'
```
a corresponding entry from the Cloudman log:
```
016-02-12 17:29:13,109 DEBUG         master:2761 S&S: AS..OK; ClouderaManager..Unstarted; Cloudgene..Unstarted; Galaxy..OK; GalaxyReports..Unstarted; Migration..Completed; Nginx..OK; NodeJSProxy..OK; PSS..Completed; Postgres..OK; ProFTPd..OK; Pulsar..Unstarted; Slurmctld..OK; Slurmd..OK; Supervisor..OK; galaxy FS..OK; galaxyIndices FS..OK; transient_nfs FS..OK;
2016-02-12 17:30:18,567 WARNING   filesystem:487  Empty disk usage for FS 'transient_nfs'
```
However, everything seems to work fine. This usually (but not always) starts occurring after a cluster is brought back up after a shutdown (never with a brand new cluster).

**Comment by afgane** [comment] 2016-02-12 19:30
When this happens, are you perhaps using an instance from T2 or C4 families?

**Comment by hackdna** [comment] 2016-02-12 19:49
Yes, with t2 and m4.

**Comment by afgane** [comment] 2016-02-12 20:29
If you have such instance up, can you paste the content from `/var/log/cloudman/cm_autorun.log`? (make sure there is no sensitive data in the pasted content)

**Comment by afgane** [comment] 2016-02-13 09:00
This should be fixed now and, for the time being, available from `cloudman-test` bucket.

**Comment by hackdna** [comment] 2016-02-17 17:20
Thanks, I'll use m3 instances until this fix is in the main CloudMan version.

**Comment by hackdna** [comment] 2016-02-18 23:23
I've tested autoscaling (min: 0, max: 2, instance type: m4.2xlarge) with cloudman-test bucket but the worker nodes failed to start with the following error message in the cluster info log:
```
23:17:28 - Adding 1 on-demand instance(s)
23:17:28 - EC2 response error when starting worker nodes: EC2ResponseError: 400 Bad Request InvalidParameterValueInvalid value 'custom_instance_type' for InstanceType.7bf99935-84b3-4bec-8517-8f95d1fcae77
```

**Comment by afgane** [comment] 2016-02-22 15:48
What about with an instance type other than m4, c4, or t2? I believe those instance types must be launched within a VPC and unless you're running the master in VPC, mixing those in won't work.

**Comment by hackdna** [comment] 2016-02-22 16:05
This was running in a VPC with m4.large master. I could test with c3.large master and c3.2xlarge workers and report back.

**Comment by afgane** [comment] 2016-02-22 16:19
If it's not too much trouble, that'd be great. Things worked in that setup when I tried it. 

How are you launching the cluster in a VPC? Could you share that script? VPC support has not been used very much so unexpected behavior could certainly creep in.

**Comment by hackdna** [comment] 2016-02-22 16:25
I'm simply using https://launch.usegalaxy.org/launch and cluster instances just end up in the default VPC. Is there a script I could use instead?

In the meantime, here's more info from `cloudman.log` with m4.large master and m4.2xlarge workers (min: 0, max 1, master not running jobs):
```
2016-02-22 16:18:41,863 DEBUG      autoscale:104  Checking if cluster too SMALL: minute:18,idle:0,total workers:0,avail workers:0,min:0,max:1
2016-02-22 16:18:41,887 DEBUG      autoscale:138  Checking if slow job turnover: queued jobs: 1, avg runtime: 0
2016-02-22 16:18:41,887 DEBUG      autoscale:60   Autoscaling UP: 1 instance(s)
2016-02-22 16:18:41,887 DEBUG         master:1266 Adding 1 custom_instance_type instance(s)
2016-02-22 16:18:41,887 INFO             ec2:431  Adding 1 on-demand instance(s)
2016-02-22 16:18:41,904 DEBUG            ec2:463  Starting instance(s) in VPC with the following command : ec2_conn.run_instances( image_id='ami-d5246abf', min_count='1', max_count='1', key_name='cloudman_key_pair', security_group_ids=['sg-53d1bc2a'], user_data(with sensitive info filtered out)=[static_images_dir: static/images
cluster_templates: [{'filesystem_templates': [{'archive_url': 'http://s3.amazonaws.com/cloudman/fs-archives/galaxyFS-20151202.tar.gz', 'type': u'volume', 'name': 'galaxy', 'roles': 'galaxyTools,galaxyData', 'size': u'30'}, {'snap_id': 'snap-c332f2b0', 'name': 'galaxyIndices', 'roles': 'galaxyIndices'}], 'name': 'Galaxy'}, {'filesystem_templates': [{'name': 'galaxy'}], 'name': 'Data'}]
ec2_port: None
master_hostname_alt: ip-172-31-9-115
storage_type: volume
is_secure: True
cluster_storage_type: volume
s3_port: None
log_level: DEBUG
static_cache_time: 360
master_public_ip: 54.210.30.29
cluster_type: Galaxy
initial_cluster_type: Galaxy
static_scripts_dir: static/scripts
debug: true
master_ip: 172.31.9.115
cluster_name: cm-test
machine_image_id: ami-d5246abf
role: worker
bucket_cluster: cm-1573993126c7bd29e256e01474053a94
boot_script_path: /opt/cloudman/boot
master_hostname: ip-172-31-9-115.ec2.internal
ec2_conn_path: /
region_name: us-east-1
region_endpoint: ec2.amazonaws.com
persistent_data_version: 3
static_favicon_dir: static/favicon.ico
deployment_version: 2
storage_size: 30
use_translogger: False
boot_script_name: cm_boot.py
services: [{'name': 'Supervisor', 'roles': ['Supervisor']}, {'name': 'Postgres', 'roles': ['Postgres']}, {'name': 'ProFTPd', 'roles': ['ProFTPd']}, {'name': 'GalaxyReports', 'roles': ['GalaxyReports']}, {'name': 'Slurmd', 'roles': ['Slurmd']}, {'name': 'Nginx', 'roles': ['Nginx']}, {'name': 'NodeJSProxy', 'roles': ['NodeJSProxy']}, {'home': '/mnt/galaxy/galaxy-app', 'name': 'Galaxy', 'roles': ['Galaxy']}, {'name': 'Slurmctld', 'roles': ['Slurmctld', 'Job manager']}]
cloud_type: ec2
custom_image_id:
cloudman_file_name: cm.tar.gz
access_key: <redacted>
global_conf: {'__file__': '/mnt/cm/cm_wsgi.ini', 'here': '/mnt/cm'}
filesystems: [{'kind': 'snapshot', 'mount_point': '/mnt/galaxyIndices', 'name': 'galaxyIndices', 'roles': ['galaxyIndices'], 'ids': ['snap-c332f2b0']}, {'kind': 'volume', 'mount_point': '/mnt/galaxy', 'name': 'galaxy', 'roles': ['galaxyTools', 'galaxyData'], 'ids': [u'vol-807be523']}]
placement: us-east-1d
template_path: templates
cloud_name: Amazon - Virginia
static_dir: static
static_style_dir: static/style
cloudman_home: /mnt/cm
bucket_default: cloudman-test
custom_instance_type: m4.large
s3_host: s3.amazonaws.com
use_lint: false
s3_conn_path: /
static_enabled: True
worker_initial_count: ], instance_type='custom_instance_type', placement='us-east-1d', subnet_id='subnet-63293c25')
2016-02-22 16:18:42,048 ERROR     connection:1202 400 Bad Request
2016-02-22 16:18:42,048 ERROR     connection:1203 <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'custom_instance_type' for InstanceType.</Message></Error></Errors><RequestID>340bb1d7-11dd-4e75-b856-d86c5a9724bf</RequestID></Response>
2016-02-22 16:18:42,049 ERROR            ec2:514  EC2 response error when starting worker nodes: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'custom_instance_type' for InstanceType.</Message></Error></Errors><RequestID>340bb1d7-11dd-4e75-b856-d86c5a9724bf</RequestID></Response>
```

**Comment by hackdna** [comment] 2016-02-22 16:45
A relevant portion of the startup log with c3.large master:
```
2016-02-22 16:38:56,621 INFO          master:932  The master instance is set to *not* execute jobs. To manually change this, use the CloudMan Admin panel.
2016-02-22 16:38:56,621 INFO             ec2:431  Adding  on-demand instance(s)
2016-02-22 16:38:56,638 DEBUG            ec2:205  Gathering instance public keys (i.e., key pairs), attempt 0
2016-02-22 16:38:56,640 DEBUG            ec2:212  Got key pair: 'cloudman_key_pair'
2016-02-22 16:38:56,646 DEBUG            ec2:176  Fetched security group ids for the first time: ['sg-53d1bc2a']
2016-02-22 16:38:56,648 DEBUG            ec2:463  Starting instance(s) in VPC with the following command : ec2_conn.run_instances( image_id='ami-d5246abf', min_count='1', max_count='', key_name='cloudman_key_pair', security_group_ids=['sg-53d1bc2a'], user_data(with sensitive info filtered out)=[static_images_dir: static/images
cluster_templates: [{'filesystem_templates': [{'archive_url': 'http://s3.amazonaws.com/cloudman/fs-archives/galaxyFS-20151202.tar.gz', 'type': u'volume', 'name': 'galaxy', 'roles': 'galaxyTools,galaxyData', 'size': u'30'}, {'snap_id': 'snap-c332f2b0', 'name': 'galaxyIndices', 'roles': 'galaxyIndices'}], 'name': 'Galaxy'}, {'filesystem_templates': [{'name': 'galaxy'}], 'name': 'Data'}]
storage_type: volume
filesystem_templates: []
is_secure: True
master_hostname_alt: ip-172-31-33-229
s3_port: None
log_level: DEBUG
static_cache_time: 360
master_public_ip: 107.23.96.201
debug: true
initial_cluster_type: Galaxy
static_scripts_dir: static/scripts
master_ip: 172.31.33.229
cluster_name: cm-test
role: worker
bucket_cluster: cm-1573993126c7bd29e256e01474053a94
boot_script_path: /opt/cloudman/boot
master_hostname: ip-172-31-33-229.ec2.internal
ec2_conn_path: /
region_name: us-east-1
region_endpoint: ec2.amazonaws.com
ec2_port: None
static_favicon_dir: static/favicon.ico
storage_size: 30
use_translogger: False
boot_script_name: cm_boot.py
cloud_type: ec2
custom_image_id:
cloudman_file_name: cm.tar.gz
access_key: <redacted>
global_conf: {'__file__': '/mnt/cm/cm_wsgi.ini', 'here': '/mnt/cm'}
template_path: templates
cloud_name: Amazon - Virginia
static_dir: static
static_style_dir: static/style
cloudman_home: /mnt/cm
bucket_default: cloudman-test
custom_instance_type:
cluster_type: Galaxy
s3_host: s3.amazonaws.com
use_lint: false
s3_conn_path: /
static_enabled: True
worker_initial_count: ], instance_type='c3.large', placement='us-east-1b', subnet_id='subnet-bdd8ed95')
2016-02-22 16:38:56,805 ERROR     connection:1202 400 Bad Request
2016-02-22 16:38:56,805 ERROR     connection:1203 <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Maximum instance count must be greater than zero</Message></Error></Errors><RequestID>82fde848-4bbd-49f9-aa2e-c65f35a33253</RequestID></Response>
2016-02-22 16:38:56,805 ERROR            ec2:514  EC2 response error when starting worker nodes: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Maximum instance count must be greater than zero</Message></Error></Errors><RequestID>82fde848-4bbd-49f9-aa2e-c65f35a33253</RequestID></Response>
```

**Comment by hackdna** [comment] 2016-02-22 16:56
Autoscaling works when selecting a worker node from the dropdown but fails when "c3.2xlarge" is specified as a "custom instance type":
```
2016-02-22 16:48:39,409 DEBUG      autoscale:138  Checking if slow job turnover: queued jobs: 1, avg runtime: 0
2016-02-22 16:48:39,409 DEBUG      autoscale:60   Autoscaling UP: 1 instance(s)
2016-02-22 16:48:39,409 DEBUG         master:1266 Adding 1 custom_instance_type instance(s)
2016-02-22 16:48:39,409 INFO             ec2:431  Adding 1 on-demand instance(s)
2016-02-22 16:48:39,426 DEBUG            ec2:463  Starting instance(s) in VPC with the following command : ec2_conn.run_instances( image_id='ami-d5246abf', min_count='1', max_count='1', key_name='cloudman_key_pair', security_group_ids=['sg-53d1bc2a'], user_data(with sensitive info filtered out)=[static_images_dir: static/images
cluster_templates: [{'filesystem_templates': [{'archive_url': 'http://s3.amazonaws.com/cloudman/fs-archives/galaxyFS-20151202.tar.gz', 'type': u'volume', 'name': 'galaxy', 'roles': 'galaxyTools,galaxyData', 'size': u'30'}, {'snap_id': 'snap-c332f2b0', 'name': 'galaxyIndices', 'roles': 'galaxyIndices'}], 'name': 'Galaxy'}, {'filesystem_templates': [{'name': 'galaxy'}], 'name': 'Data'}]
ec2_port: None
master_hostname_alt: ip-172-31-33-229
storage_type: volume
is_secure: True
cluster_storage_type: volume
s3_port: None
log_level: DEBUG
static_cache_time: 360
master_public_ip: 107.23.96.201
cluster_type: Galaxy
initial_cluster_type: Galaxy
static_scripts_dir: static/scripts
debug: true
master_ip: 172.31.33.229
cluster_name: cm-test
machine_image_id: ami-d5246abf
role: worker
bucket_cluster: cm-1573993126c7bd29e256e01474053a94
boot_script_path: /opt/cloudman/boot
master_hostname: ip-172-31-33-229.ec2.internal
ec2_conn_path: /
region_name: us-east-1
region_endpoint: ec2.amazonaws.com
persistent_data_version: 3
static_favicon_dir: static/favicon.ico
deployment_version: 2
storage_size: 30
use_translogger: False
boot_script_name: cm_boot.py
services: [{'name': 'Supervisor', 'roles': ['Supervisor']}, {'name': 'Postgres', 'roles': ['Postgres']}, {'name': 'ProFTPd', 'roles': ['ProFTPd']}, {'name': 'GalaxyReports', 'roles': ['GalaxyReports']}, {'name': 'Slurmd', 'roles': ['Slurmd']}, {'name': 'Nginx', 'roles': ['Nginx']}, {'name': 'NodeJSProxy', 'roles': ['NodeJSProxy']}, {'home': '/mnt/galaxy/galaxy-app', 'name': 'Galaxy', 'roles': ['Galaxy']}, {'name': 'Slurmctld', 'roles': ['Slurmctld', 'Job manager']}]
cloud_type: ec2
custom_image_id:
cloudman_file_name: cm.tar.gz
access_key: <redacted>
global_conf: {'__file__': '/mnt/cm/cm_wsgi.ini', 'here': '/mnt/cm'}
filesystems: [{'kind': 'snapshot', 'mount_point': '/mnt/galaxyIndices', 'name': 'galaxyIndices', 'roles': ['galaxyIndices'], 'ids': ['snap-c332f2b0']}, {'kind': 'volume', 'mount_point': '/mnt/galaxy', 'name': 'galaxy', 'roles': ['galaxyTools', 'galaxyData'], 'ids': [u'vol-f86e3c27']}]
placement: us-east-1b
template_path: templates
cloud_name: Amazon - Virginia
static_dir: static
static_style_dir: static/style
cloudman_home: /mnt/cm
bucket_default: cloudman-test
custom_instance_type:
s3_host: s3.amazonaws.com
use_lint: false
s3_conn_path: /
static_enabled: True
worker_initial_count: ], instance_type='custom_instance_type', placement='us-east-1b', subnet_id='subnet-bdd8ed95')
2016-02-22 16:48:39,838 ERROR     connection:1202 400 Bad Request
2016-02-22 16:48:39,838 ERROR     connection:1203 <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'custom_instance_type' for InstanceType.</Message></Error></Errors><RequestID>ba9942fb-0bb9-4a6f-ae11-0c6dc3272ba2</RequestID></Response>
2016-02-22 16:48:39,838 ERROR            ec2:514  EC2 response error when starting worker nodes: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'custom_instance_type' for InstanceType.</Message></Error></Errors><RequestID>ba9942fb-0bb9-4a6f-ae11-0c6dc3272ba2</RequestID></Response>
```

**Comment by afgane** [comment] 2016-02-22 16:58
Thanks - I'll look into all of this.

With the VPC - I guess your account doesn’t support for _Classic_ EC2 so all instances go into VPC. I have to manually launch an instance into VPC and it's complicated at best (but since we're working on a [new launcher](https://github.com/galaxyproject/cloudlaunch/issues/49), I didn't want to put much effort into this one any more).

**Comment by hackdna** [comment] 2016-02-22 17:17
Thank you! Yes, I have a newer AWS account where instances go into a VPC by default. The new launcher proposal looks great, I'd love to test it when it becomes available.

**Comment by afgane** [comment] 2016-02-25 17:35
Both of these issues should be fixed now. Thanks for reporting them.

**Closed by afgane** 2016-02-25 17:35 UTC

**Comment by hackdna** [comment] 2016-02-25 23:05
Yes, I've tested (master: t2.medium, worker: m4.2xlarge) and both were fixed. Thank you!
